name = "schedule-notifier"
main = "src/worker.ts"
compatibility_date = "2023-07-21"

compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
logpush = true

browser = { binding = "BROWSER", type = "browser" }

[triggers]
crons = ["0 */3 * * *"]
