name = "schedule-notifier"
main = "src/worker.ts"
compatibility_date = "2023-06-10"

node_compat = true
workers_dev = false

browser = { binding = "BROWSER", type = "browser" }

[triggers]
crons = ["0 */3 * * *"]
