name: lint and test

on:
  push:

permissions:
  contents: read
jobs:
  test:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
      - run: deno lint
      - run: deno fmt